# Sentiment Analysis

In [1]:
import os
print(os.path.abspath("arg_mining/ml_algorithms/ML/datasets/test.conll"))

c:\Users\huonc\Desktop\python\mining_project\arg_mining\ml_algorithms\ML\arg_mining\ml_algorithms\ML\datasets\test.conll

In [2]:
train_path = "datasets/train.conll"
test_path = "datasets/test.conll"
val_path = "datasets/validation.conll"
with open(train_path, encoding="utf-8") as f:
    train_data = f.read()

with open(test_path, encoding = "utf-8") as f:
    test_data = f.read()

with open(val_path, encoding = "utf-8") as f:
    val_data = f.read()

In [ ]:
#test with full dataset (no splitting)
full_data_path = "datasets/full_original_text.txt"
with open(full_data_path, encoding = "utf-8") as f:
    full_data = f.read()

'====================\nPost 1: CMV: I genuinely can\'t trust Israel on whatever they say anymore\nAuthor: ExtremeAcceptable289Post Text: So I\'ve been keeping up with Palestine news lately, and it\'s come to my attention that I feel I just can\'t trust Israel on anything anymore, even though it\'d be absurd to not trust them just because.\n\nThey\'ve lied on so many thing it\'s crazy:\n\nShereen Abu Akleh\n\nThe 40 beheaded babies (they also got Biden to lie about it)\n\nThe flour massacre\n\nThe al-shifa hospital incident in which an Israeli impersonated an al-Shifa doctor along with the edited video after Nov 2023 siege\n\nThe al-Ahli hospital faked voice call\n\nThe 15 executed aid workers \n\nHamas stealing aid (turns out an israeli funded gang did it)\n\nThe many, many times of "Palewood" lies (in which they later retacted/got debunked)\n\nThe gaza ministry of health being lies\n\nThe numbers of Hamas millitants dead (American intelligence and independent org says it is way less, and the number they claim is actually the number of males &gt;15)\n\nHamas shooting people trying to get aid \n\nThe white phosphorus\n\nEven things that should be trusted like the clips they send I just cant trust. \n++++++++++++++++++++\n1 : DeltaBot\nComment: /u/ExtremeAcceptable289 (OP) has awarded 1 delta(s) in this post.\n\nAll comments that earned deltas (from OP or other users) are listed [here](/r/DeltaLog/comments/1l7fzn0/deltas_awarded_in_cmv_i_genuinely_cant_trust/), in /r/DeltaLog.\n\nPlease note that a change of view doesn\'t necessarily mean a reversal, or that the conversation has ended.\n\n^[Delta\xa0System\xa0Explained](https://www.reddit.com/r/changemyview/wiki/deltasystem) ^| ^[Deltaboards](https://www.reddit.com/r/changemyview/wiki/deltaboards)\n\n++++++++++++++++++++\n2 : Plus_Bison_7091\nComment: Your list conflates rumor, Hamas propaganda, and evolving official narratives; debunking requires nuance, not blanket dismissal.\n\nFrom the points it’s also unclear to me what you accuse them of lying about. Furthermore, who do you mean by „Israel“ - the government or the IDF because the points that you have given are mostly not based on official statements by any Israeli institution. \n\n1. Shireen Abu Akleh\n\nIsraeli investigations concluded there was “a high possibility” she was accidentally struck by IDF fire aimed at armed suspects. While Al Jazeera found no hostile militants in her vicinity and suggested potential intentional targeting, they are not a reliable source￼. While Israel’s initial denial was misleading, IDF did not lie—they eventually acknowledged IDF fire as likely cause.\n\n2. The “40 beheaded babies”\n\nThis narrative originated from unverified Israeli field reports. Most likely a journalist lost in translation when first responders talked about „40 dead children, some of them beheaded“.  Everyone ran with it but Israel never said a thing. \n\nThere is no credible photographic or forensic evidence ever supported claims of infants being beheaded; what was observed were bodies discovered post-mortem with visible trauma, not premeditated beheadings. Which means children were found without a head - we don’t know how they lost it! President Biden’s repeated references were based on these flawed early accounts, not Israel’s official statements, which never confirmed beheading narratives—so the lie is with the rumor, not Israeli officials.\n\n3. The “flour massacre”\n\nMultiple eyewitnesses and U.N. investigators confirmed Israeli troops fired live rounds into crowds seeking aid, resulting in at least 112 deaths—something Israel initially downplayed but later partially conceded￼. BBC and UN reports found large numbers of gunshot wounds consistent with IDF weaponry￼. Israel’s narrative shifted from warning shots to admitting incidents of live fire, showing evolution rather than deliberate falsehood.\n\n4. Al‑Shifa hospital impersonator video\n\nThe widely circulated video claiming an “Israeli” nurse inside Al‑Shifa was thoroughly debunked by France 24 and OSINT investigators as staged propaganda. No verified evidence supports allegations of IDF impersonating medical staff. Israel never officially confessed to such an impersonation—it was fabricated by third parties and amplified in partisan media.\n\n5. Al‑Ahli hospital “fake” voice call\n\nThe claim alleging staged Israeli propaganda around a doctored Gaza Health Ministry voice call lacks credible evidence. Investigations show fake IDF “confession” posts, not Israeli government admissions. Al‑Ahli’s  incident in Oct 2023 remains disputed but was never supported by Israeli military inauthentic audio.\n\n6. The “15 executed aid workers”\n\nI wanted to summarize [this article](https://steadyhq.com/de/u-m/posts/a90081a0-2186-495b-aa5a-45d6f84e7816) by a German ex-military expert but I think it’s needed to read the full text. It explains well the IDF statements and the events what happened. \n\n7. Hamas stealing aid (Israeli-funded gang)\n\nThere are estimates that about 60 percent of the aid deliveries that went into the Gaza Strip were stolen by Hamas. There are dozens, if not hundreds, of videos—mind you, from Palestinian sources—that show men armed with assault rifles hijacking and driving away trucks. Proudly brandishing their weapons, standing on the cargo. We can debate who these weapon brandishing dudes are - but my bets are on Hamas. \n\n8. “Pallywood” staged scenes\n\nClaims of staged Palestinian casualties (“Pallywood”) often stem from extreme fringe videos and have been refuted by credible outlets like France\u202f24 and HonestReporting￼. While minor inaccuracies occur in war-zone footage, there is no proof of widespread Israeli-funded fakery. Israel does not retract major events based on such rumors.\n\n9. Gaza Ministry of Health lying\n\nThe Gaza Health Ministry, run by Hamas, has a long-documented history of inflating civilian death tolls, including during the 2023 October hospital incident. Independent monitors stress these figures often lack external verification and must be treated cautiously. Israel, for its part, provides its own counts—figures differ, but that doesn’t equate to Israel lying, rather reflects differing data sources.\n\n10. Hamas militants kill count\n\nIsrael carefully distinguishes between male civilian deaths and confirmed militant casualties. American and independent intelligence sources challenge high militant death estimates, noting large portions may include non-combatants counted by Hamas-aligned sources. Israel’s claims of militants killed are based on field intelligence and ID cards recovered—complex but not inherently deceptive.\n\n11. Hamas shooting aid‑seekers\n\nIDF-released drone footage shows armed individuals firing at crowds seeking aid in Khan Younis, suggesting Hamas-linked groups have targeted civilians to disrupt aid.\n\nThe truth is multifaceted and not an Israeli cover-up.\n\n12. White phosphorus use\n\nDespite accusations, there is no confirmed evidence Israel used white phosphorus in Gaza in 2024–25 from independent war‑crime monitoring groups. Israel denies deploying it, and no credible OSINT or forensic reports verify its use. Until those surface, the claim remains unsubstantiated rumor.\n\nUgh, I had to write this twice because I had to go back and check my sources. \n\nIn summary, imo the IDF or Israeli government is not deliberately lying. In fact, most times they clearly state that they are “investigating” but sadly they only come out with results far after the rumors are already made facts. Also, in most cases the IDF is able to admit fault. They admitted on October 7, some Israelis (like 4 or something) died by friendly fire (which is from a combat viewpoint completely normal in this chaos) and also they admitted within hours when they shot 3 of the hostages who escaped in Gaza by accident. \n\nWhat I recommend you and everyone is to stay open to more information and wait until all sides have their side of the story out to make judgement. \n\nThe IDF is not perfect but there’s a lot of anti Israeli propaganda and fake news out there. Important not to conflate real criticism wirh made up stories.\n\n++++++++++++++++++++\n3 : Kman17\nComment: So a really basic question for you is this: if you do not trust Israel, what is your source of truth there? What makes you think it is free from bias?\n\nTo simplify a little bit, there are basically four categories of sources here:\n\n* What Israel says \n* What the US says\n* What ‘international’ entities (comprised of mostly European and Middle Eastern interests) say\n* What Palestine says \n\nThose four entities are in order of “everything Israel says is true” to “everything Israel says is false”.\n\nThe U.S. generally sides more with Israel but critiques, and Middle East influenced European agencies generally sides more with a Palestine but critiques.\n\nThe most probable reality is somewhere between the U.S. and EU assessment - and most of them have a more mixed assessment on all the topics you raised.\n\nNo entity here is free from bias. The NPOs and “international” entities have plenty.\n\nThere is a very, very basic truth here which is that Hamas *does* use un-uniformed soldiers, and they *do* hide amongst civilians. Like that’s not a debate.\n\nThat in turn makes every single incident a he said she said, where no one has correct intel but everyone has a narrative.\n\nYou must also recognize that Palestines strategy *is* a PR war. They instigated Israel in a way that absolutely necessitated military response, and their goal is to use the response in court of opinion to weaken Israeli alliances. That is also just undeniable.\n\nBe careful with social media accounts. There’s this temptation to think Reddit / TikTok / whatever are delivering unfiltered news from the ground, but those are astroturfed like crazy by state level actors pumping out Palestinian propaganda.\n\nI would not want to suggest you review is you should read evey Israeli statement as gospel truth - there’s obviously a slant.\n\nBut you shouldn’t assume that the moment you find hyperbole or incorrect report it means that the side becomes entirely untrustworthy and by extension the other side becomes definitionally  right.\n\n++++++++++++++++++++\n4 : Falernum\nComment: You are listing a whole lot of things but let\'s start with the first: Shireen Abu Akleh\n\nIsrael stated they shot near her and Palestinians shot near her, and that they weren\'t sure who shot her.  This is true!\n\nPalestinian police never made the bullet available to check who shot her.  Israeli internal investigations said it was quite possible they had done so.  The US concluded that Israeli gunfire most likely hit her based on the Israeli investigation.\n\nI don\'t understand why you say that means Israel lied\n They said they weren\'t sure and they might have.  They weren\'t sure.  That\'s truth\n\n++++++++++++++++++++\n5 : Xolver\nComment: I\'m having problems knowing exactly what bar needs to be met to change your mind, since your post is basically saying you can\'t trust Israel and then listing a few instances, some of which Israel lied about and some of which Israel decidedly *did not* lie about. Others are trying to tackle your points one by one so I\'ll try something different.\n\n\nIf the bar is whether Israel never lies or makes mistakes - nope, nothing will change your mind, since it does/has.\n\n\nIf the bar is whether Israel is mostly truthful - it is. If you think otherwise, it would be prudent to say what sort of statistical analysis you performed over Israeli messaging in general that included both truths and lies.\n\n\nIf the bar is whether it\'s more truthful than Hamas or Palestinians in general... Boy oh boy. This isn\'t even in the same ball park and I think no amount of evidence could persuade you if you think otherwise. Hamas lies as policy, and any non lie is the exception and not the rule. Many lies are so ridiculously over the top such as saying a leader is just fine for months before admitting he was killed in an attack. I hope you\'re not deluded enough to think this bar is one Israel doesn\'t pass.\n\n++++++++++++++++++++\n6 : skejindo\nComment: You’ve completely drunk the kool aid here. Qatar, Hamas, and the Muslim brotherhood spend billions on propaganda and news outlets to convince you of exactly this.\xa0\n\n++++++++++++++++++++\n7 : Appropriate_Gate_701\nComment: &gt;Shereen Abu Akleh\n\nIsrael said that they likely didn\'t kill her, but that they\'d investigate.  Then they completed the investigation and found that they accidentally killed her.\n\n&gt;The 40 beheaded babies (they also got Biden to lie about it)\n\nNot the Israeli government, but people responding and reporting on it being misinterpreted.  There were beheaded babies, and there were burned babies.  But there weren\'t 40 beheaded babies.\n\n&gt;The flour massacre\n\nA whole bunch of people ran on an aid convoy and were shot at by people protecting the aid convoy.  This is a tragedy, but also why you don\'t attack an aid convoy.\n\n&gt;Hamas stealing aid (turns out an israeli funded gang did it)\n\nThat\'s not true.  Hamas has been stealing aid.  Other groups have also been stealing aid.  There\'s been a lot of stealing aid.  Which explains the fact that people were running at an aid convoy and that the convoys were heavily armed.\n\n&gt;The many, many times of "Palewood" lies (in which they later retacted/got debunked)\n\nLet\'s have some examples.\n\n&gt;The numbers of Hamas millitants dead (American intelligence and independent org says it is way less, and the number they claim is actually the number of males &gt;15)\n\nYou\'re just spitballing\n\n&gt;Hamas shooting people trying to get aid\n\nThis literally happened.  For the reasons listed above.  Whoever controls aid controls the strip.  Hamas losing control of the aid has led them to attack Gazans who are trying to get aid elsewhere and not pay Hamas\'s exorbitant prices on food and supplies that should be free.\n\n&gt;The white phosphorus\n\nThis didn\'t happen\n\n++++++++++++++++++++\n8 : Commercial_Lead_7406\nComment: Some points of accuracy on some of your claims.\n\n40 beheaded babies - No Israeli source ever claimed this. An independent journalist erroneously made this claim early on. The Israelis claimed 40 children killed, some beheaded. Final number of child casualties was around 36, so accurate. It is factually true that at least one child was found decapitated. Others were found dismembered.\n\n&gt;\n\nThe Commission reviewed photos of the burnt skull of a decapitated woman found in Kfar Aza. The Commission also reviewed photos of a 12-year-old girl who was shot in the head and then decapitated.\n\n&gt;A first responder, working at a central identification centre for victims of 7 October, told the Commission that containers with “special bodies” were received at the centre. He explained that these bodies included the bodies of children with severed body parts. The centre also reportedly received bags of severed body parts.\n\n[https://www.ohchr.org/sites/default/files/documents/hrbodies/hrcouncil/sessions-regular/session56/a-hrc-56-crp-3.pdf](https://www.ohchr.org/sites/default/files/documents/hrbodies/hrcouncil/sessions-regular/session56/a-hrc-56-crp-3.pdf)\n\nThe fake Al-Shifa doctor wasn\'t from official Israeli sources, just some social media poster.\n\nHamas stealing aid. They do steal aid. Israeli funded gangs do too, but Hamas absolutely steals aid.\n\nThe Al-Ahli bombing was falsely reported as 500 casualties from Israeli munitions when in fact actual casualties were unknown, likely far lower, and the munition was likely a PIJ misfire.\n\n[https://www.hrw.org/news/2023/11/26/gaza-findings-october-17-al-ahli-hospital-explosion](https://www.hrw.org/news/2023/11/26/gaza-findings-october-17-al-ahli-hospital-explosion)\n\nThe Gaza MoH has published questionable numbers and has made false statements. The MoH also uses some fairly unreliable methods to report casualties (google docs submissions) and makes no distinction between fighters and civilians. Total numbers are claimed to be broadly accurate, but civilian vs combatant ratios are not well known.\n\n++++++++++++++++++++\n9 : Mortimer1234\nComment: This is war, and with war comes propaganda. For some of these events, you calling them Israeli lies implies that you have chosen to believe Hamas propaganda instead. For example Hamas stealing aid. This is not a lie, and has absolutely been happening. There are videos of Hamas militants shooting people trying to receive aid. There’s a reason why Palestinians have been protesting against Hamas, and many of them have been murdered for doing so. \n\n“Israel lies” has simply become a convenient slogan for those on the anti-Israel train to shout whenever confronted with “facts” (I use that word lightly, as I don’t think either side is ever going to present unaltered or non-cherry picked information), in the same vain that the MAGA crowd blames the news whenever you point of all of the shit that Trump has done. A key part of propaganda is causing your base to distrust the word of your enemy, which is seen in both sides here. You’re just falling for the Hamas side, in this case\n\n++++++++++++++++++++\n10 : ArmThick7835\nComment: Not familiar with her name.  \n40 beheaded babies was never something that Israel has ever claimed. It literally was just romurs from lifeless Pro-Israelis, though babies HAVE been beheaded  \nIDF, unlike your sources, released a statement saying that 10 Palestinians have been close to them in a threatning way so the opened in fire; chaos happened and unfortunately, as like in any war, there were civillian victims; Israel has never denied this.  \nHuh?  \nIt was not fake LMAO, unless your source is Al-Jazeera (banned in both israelk and Palestine btw; Hamas propaganda pull) no source has ever confirmed this is fake  \nIt was a deadly mistake which happens in every war and the IDF soldiers responsible for that were immediately taken off service (according to both Israeli and Palestinian sources).  \nLol. Hamas stole aid ENDLESS times. [https://www.idf.il/en/mini-sites/israel-at-war/all-articles/watch-hamas-members-beat-civilians-and-steal-humanitarian-aid/](https://www.idf.il/en/mini-sites/israel-at-war/all-articles/watch-hamas-members-beat-civilians-and-steal-humanitarian-aid/) [https://www.jns.org/abbas-confirms-hamas-gangs-stealing-gaza-aid/](https://www.jns.org/abbas-confirms-hamas-gangs-stealing-gaza-aid/) [https://www.youtube.com/watch?v=NBjvYkNzuAA](https://www.youtube.com/watch?v=NBjvYkNzuAA)  \nWhich lies exactly?  \nGaza Ministry IS full of lies. Hamas is a totalirian regime and therefore every government ministry is directly controlled by them. Multiple times, they have added names for more then 10 times on the same list, recognised Men as Women and Children, didn\'t spill casualties to terrorists and civillians as in international law (cause theyre a terror group)  \nI mean, accordingf to Hamas itself, they lost a HUGE number and are missing people  \nIt did  \n?\n\nYou cant trust anything because the Palestinian propaganda machine got to you.\n\n++++++++++++++++++++\n11 : ADP_God\nComment: This is not a CMV, but if you are trying to argue that it is somehow less credible than other sources from the war, I would encourage you to look up all the lies that have been told by Hamas up till this point. They\'re very easy to find if you search. Look at all the casualty counts they walked back, or the fake videos with repeated actors theyve put out, just to name a few. Israel has independant journalism and left wing media.\n\n++++++++++++++++++++\n12 : BuffZiggs\nComment: How do you feel you reached the objective truth on the matters you listed?\n\n++++++++++++++++++++\n13 : oshaboy\nComment: I feel like you are mixing up 3 categories in the list. Actual Lies, Unsubstantiated Rumors/Mistakes and "Thing I claim are lies with

In [ ]:
#clean txt full_data file
import re
def clean_text(data):
    #line separators
    data = re.sub(r'^\s*={5,}.*?\n', '', data, flags=re.MULTILINE)
    data = re.sub(r'^\s*\+{5,}.*?\n', '', data, flags=re.MULTILINE)

    #reddit structure
    data = re.sub(r'\[.*?\]\(.*?\)', '', data)
    data = re.sub(r'Post \d+:\s*CMV:', '', data)
    data = re.sub(r'Author:\s*[^P]+?Post Text:', '', data, flags=re.DOTALL)
    data = re.sub(r'Comment:', '', data)

    #reddit bot
    delta_patterns = [
        r'^.*DeltaBot.*$',
        r'^.*has awarded \d+ delta\(s\).*$',
        r'^.*All comments that earned deltas.*$',
        r'^.*Delta System Explained.*$',
        r'^.*Deltaboards.*$',
        r'^.*Please note that a change of view.*$',
    ]
    for pattern in delta_patterns:
        data = re.sub(pattern, '', data, flags=re.MULTILINE)
    data = re.sub(r'^\s*\d+\s*:\s*.*$', '', data, flags=re.MULTILINE)

    #specific punctuation
    data = re.sub(r'&gt;', ' ', data)
    data = re.sub(r'\^|\^', '', data) 
    data = re.sub(r'\|', '', data)   
    data = re.sub(r',,', '', data)   
    data = re.sub(r"''", '', data)   
    data = re.sub(r'[\'"]', '', data) #maybe affect the negation
    data = re.sub(r'[\u201E\u201C\-()]', '', data)
    data = re.sub(r'[,:;]', '', data)

    #keep whitespace
    data = re.sub(r'\s+', ' ',data).strip()

    return data

data = clean_text(full_data)

In [24]:
with open("datasets/full_text_cleaned.txt", encoding = "utf-8", mode = "w") as f:
    f.write(data)

In [25]:
import pandas as pd
def text_to_dataframe(text):
    sentences = re.split(r'(?<=[.!?])\s+', text)
    sentences = [s.strip() for s in sentences if s.strip()]
    df = pd.DataFrame(sentences, columns = ['sentences'])
    return df

df = text_to_dataframe(data)

In [26]:
df

                                               sentences
0      I genuinely cant trust Israel on whatever they...
1      Theyve lied on so many thing its crazy Shereen...
2      Your list conflates rumor Hamas propaganda and...
3      From the points it’s also unclear to me what y...
4      Furthermore who do you mean by Israel the gove...
...                                                  ...
69078  The thrill of discovery instantly ruined by th...
69079                                     Pass the mint.
69080  There will be wars over preserving these ancie...
69081  My shower thought addition to this is what if ...
69082                                          [deleted]

[69083 rows x 1 columns]

In [ ]:
#with open("datasets/full_text_cleaned.txt", encoding = "utf-8", mode = "w") as f:
    #f.write(data)

In [3]:
#extract first column directly from conll files
def get_first_column(data):
    lines = data.strip().split('\n')
    first_col = []

    for i in lines:
        if i.strip():
            cols = i.split('\t')
            first_col.append(cols[0])

    return first_col

train_first_col = get_first_column(train_data)
test_first_col = get_first_column(test_data)
val_first_col = get_first_column(val_data)

len(train_first_col), len(test_first_col), len(val_first_col)

(943056, 236923, 1179979)

In [4]:
#join words to form sentence separated by tab
'''
open the conll file then remove whitespace, tabs, newline
there is only 1 column in the conll files so it'll just append those words into current_sentence
then join the current word to another word below to make a sentence
the final else indicates the last word of a sentence
'''
def read_conll_file(file_path):
    sentences = []
    current_sentence = []
    with open(file_path, encoding='utf-8') as f:
        for line in f:
            line = line.lower()
            line = line.strip()
            if line:
                parts = line.split('\t')
                word = parts[0]
                current_sentence.append(word)
            else:
                if current_sentence:
                    sentences.append(' '.join(current_sentence))
                    current_sentence = []

    if current_sentence:
        sentences.append(' '.join(current_sentence))
    return sentences

train_sentences = read_conll_file("datasets/train.conll")
test_sentences = read_conll_file("datasets/test.conll")
val_sentences = read_conll_file("datasets/validation.conll")
test_sentences[:10]

['comment i live in an agricultural area of my state i am appreciative of alllllll the crap alllll the farmers ranchers and producers deal with its alot',
 'generally american cities have a lot of really awesome neighborhoods the transit to get from one to the other is the commonly missing part and also lots of americans live in the suburbs which often wont have nice neighborhoods even',
 'comment americanflagscom some they are kind of pricy but were running a sale soon',
 '14 ronmckelvey',
 'there is something wrong with our culture and we need some serious introspection',
 'comment removed',
 'comment my sister had the knack for finding 4 leaf clovers she would find multiples all the time her husband worked a dangerous job and wore a 4 leaf clover for luck when the clover would wilt she would just go and find another no problem',
 '19 nkpstudios',
 'comment this is a subreddit for genuine discussion',
 '9 tiger0204']

In [5]:
#remove reddit usernames (elements start with a number)
train_sentences = [item for item in train_sentences if not item.split()[0].isdigit()]
test_sentences = [item for item in test_sentences if not item.split()[0].isdigit()]
val_sentences = [item for item in val_sentences if not item.split()[0].isdigit()]
train_sentences[:5]

['comment my grandparents greatestwhatever was before greatest generation used the gesture as well as regularly saying shame on you or you should be ashamed of yourself pretty often and it was very much considered the appropriate parenting stylei read a lot of early 20th century and late 19th century popular lit kids books dime novels magazine fiction and there were frequent scenes with similar language as an older gen x i heard it from grandparents and teachers and nuns but less from my parents silents as i think they had started to recognize that excessive guilt and shame is harmful',
 'comment its grey and cloudy today anyway',
 'comment i assume you meant greet',
 'violators will be fed to the bear',
 'i am not a personal fan of it on myself i literally dont care about it on anyone else though']

In [6]:
#vocab to keep
negation_words = [
    "not", "no", "never", "none", "nothing", "neither", "nor",
    "hardly", "scarcely", "barely", "without"
]
intensifiers = [
    "very", "really", "extremely", "quite", "so", "too", "just",
    "absolutely", "totally", "incredibly", "barely", "fairly", "almost", "nearly"
]
modal_verbs = [
    "could", "would", "should", "might", "may", "must", "can", "shall", "will"
]
auxiliary_verbs = [
    "is", "are", "was", "were", "be", "been", "being", "am",
    "do", "does", "did", "have", "has", "had"
]
pronouns = [
    "i", "you", "we", "they", "he", "she", "it",
    "me", "us", "them", "my", "your", "our", "their",
    "mine", "yours", "his", "hers", "its"
]
conjunctions = [
    "but", "although", "though", "yet", "while", "whereas"
]
subjective_adverbs = [
    "always", "never", "sometimes", "often", "seldom",
    "unfortunately", "fortunately", "luckily", "sadly", "happily"
]
exception_words = (
    negation_words +
    intensifiers +
    modal_verbs +
    auxiliary_verbs +
    pronouns +
    conjunctions +
    subjective_adverbs
)
exception_words[:10]

['not',
 'no',
 'never',
 'none',
 'nothing',
 'neither',
 'nor',
 'hardly',
 'scarcely',
 'barely']

### Preprocess Text

1. source text
* data cleaning
    * identify noise
    * noise removal
    * character normalization
    * data masking*
* linguistic processing
    * tokenization
    * POS tagging
    * stopwords
    * lemmatization
    * named-entity recognition

In [7]:
import pandas as pd
import nltk 
nltk.download('all')
from nltk.sentiment.vader import SentimentIntensityAnalyzer
from nltk.corpus import stopwords 
from nltk.tokenize import word_tokenize 
from nltk.stem import WordNetLemmatizer

stop_words = set(stopwords.words("english"))
lemmatizer = WordNetLemmatizer()

def preprocess_text(text):
    tokens = word_tokenize(text)
    filtered_tokens = [token for token in tokens if token.lower() not in stop_words]
    lemmatized_tokens = [lemmatizer.lemmatize(token) for token in filtered_tokens]
    return " ".join(lemmatized_tokens)

train_processed = [preprocess_text(sentence) for sentence in train_sentences]
test_processed = [preprocess_text(sentence) for sentence in test_sentences]
val_processed = [preprocess_text(sentence) for sentence in val_sentences]

len(train_processed), len(test_processed), len(val_processed)

[nltk_data] Downloading collection 'all'
[nltk_data]    |
[nltk_data]    | Downloading package abc to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package abc is already up-to-date!
[nltk_data]    | Downloading package alpino to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package alpino is already up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_eng to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_eng is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_ru is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_rus to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_rus is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package basque_grammars to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package basque_grammars is already up-to-date!
[nltk_data]    | Downloading package bcp47 to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package bcp47 is already up-to-date!
[nltk_data]    | Downloading package biocreative_ppi to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package biocreative_ppi is already up-to-date!
[nltk_data]    | Downloading package bllip_wsj_no_aux to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package bllip_wsj_no_aux is already up-to-date!
[nltk_data]    | Downloading package book_grammars to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package book_grammars is already up-to-date!
[nltk_data]    | Downloading package brown to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package brown is already up-to-date!
[nltk_data]    | Downloading package brown_tei to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package brown_tei is already up-to-date!
[nltk_data]    | Downloading package cess_cat to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package cess_cat is already up-to-date!
[nltk_data]    | Downloading package cess_esp to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package cess_esp is already up-to-date!
[nltk_data]    | Downloading package chat80 to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package chat80 is already up-to-date!
[nltk_data]    | Downloading package city_database to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package city_database is already up-to-date!
[nltk_data]    | Downloading package cmudict to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package cmudict is already up-to-date!
[nltk_data]    | Downloading package comparative_sentences to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package comparative_sentences is already up-to-
[nltk_data]    |       date!
[nltk_data]    | Downloading package comtrans to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package comtrans is already up-to-date!
[nltk_data]    | Downloading package conll2000 to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package conll2000 is already up-to-date!
[nltk_data]    | Downloading package conll2002 to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package conll2002 is already up-to-date!
[nltk_data]    | Downloading package conll2007 to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package conll2007 is already up-to-date!
[nltk_data]    | Downloading package crubadan to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package crubadan is already up-to-date!
[nltk_data]    | Downloading package dependency_treebank to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package dependency_treebank is already up-to-date!
[nltk_data]    | Downloading package dolch to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package dolch is already up-to-date!
[nltk_data]    | Downloading package english_wordnet to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package english_wordnet is already up-to-date!
[nltk_data]    | Downloading package europarl_raw to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package europarl_raw is already up-to-date!
[nltk_data]    | Downloading package extended_omw to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package extended_omw is already up-to-date!
[nltk_data]    | Downloading package floresta to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package floresta is already up-to-date!
[nltk_data]    | Downloading package framenet_v15 to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package framenet_v15 is already up-to-date!
[nltk_data]    | Downloading package framenet_v17 to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package framenet_v17 is already up-to-date!
[nltk_data]    | Downloading package gazetteers to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package gazetteers is already up-to-date!
[nltk_data]    | Downloading package genesis to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package genesis is already up-to-date!
[nltk_data]    | Downloading package gutenberg to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package gutenberg is already up-to-date!
[nltk_data]    | Downloading package ieer to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package ieer is already up-to-date!
[nltk_data]    | Downloading package inaugural to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package inaugural is already up-to-date!
[nltk_data]    | Downloading package indian to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package indian is already up-to-date!
[nltk_data]    | Downloading package jeita to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package jeita is already up-to-date!
[nltk_data]    | Downloading package kimmo to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package kimmo is already up-to-date!
[nltk_data]    | Downloading package knbc to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package knbc is already up-to-date!
[nltk_data]    | Downloading package large_grammars to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package large_grammars is already up-to-date!
[nltk_data]    | Downloading package lin_thesaurus to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package lin_thesaurus is already up-to-date!
[nltk_data]    | Downloading package mac_morpho to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package mac_morpho is already up-to-date!
[nltk_data]    | Downloading package machado to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package machado is already up-to-date!
[nltk_data]    | Downloading package masc_tagged to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package masc_tagged is already up-to-date!
[nltk_data]    | Downloading package maxent_ne_chunker to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package maxent_ne_chunker is already up-to-date!
[nltk_data]    | Downloading package maxent_ne_chunker_tab to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package maxent_ne_chunker_tab is already up-to-
[nltk_data]    |       date!
[nltk_data]    | Downloading package maxent_treebank_pos_tagger to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package maxent_treebank_pos_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    | Downloading package maxent_treebank_pos_tagger_tab to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package maxent_treebank_pos_tagger_tab is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package moses_sample to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package moses_sample is already up-to-date!
[nltk_data]    | Downloading package movie_reviews to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package movie_reviews is already up-to-date!
[nltk_data]    | Downloading package mte_teip5 to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package mte_teip5 is already up-to-date!
[nltk_data]    | Downloading package mwa_ppdb to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package mwa_ppdb is already up-to-date!
[nltk_data]    | Downloading package names to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package names is already up-to-date!
[nltk_data]    | Downloading package nombank.1.0 to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package nombank.1.0 is already up-to-date!
[nltk_data]    | Downloading package nonbreaking_prefixes to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package nonbreaking_prefixes is already up-to-date!
[nltk_data]    | Downloading package nps_chat to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package nps_chat is already up-to-date!
[nltk_data]    | Downloading package omw to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package omw is already up-to-date!
[nltk_data]    | Downloading package omw-1.4 to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package omw-1.4 is already up-to-date!
[nltk_data]    | Downloading package opinion_lexicon to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package opinion_lexicon is already up-to-date!
[nltk_data]    | Downloading package panlex_swadesh to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package panlex_swadesh is already up-to-date!
[nltk_data]    | Downloading package paradigms to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package paradigms is already up-to-date!
[nltk_data]    | Downloading package pe08 to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package pe08 is already up-to-date!
[nltk_data]    | Downloading package perluniprops to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package perluniprops is already up-to-date!
[nltk_data]    | Downloading package pil to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package pil is already up-to-date!
[nltk_data]    | Downloading package pl196x to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package pl196x is already up-to-date!
[nltk_data]    | Downloading package porter_test to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package porter_test is already up-to-date!
[nltk_data]    | Downloading package ppattach to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package ppattach is already up-to-date!
[nltk_data]    | Downloading package problem_reports to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package problem_reports is already up-to-date!
[nltk_data]    | Downloading package product_reviews_1 to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package product_reviews_1 is already up-to-date!
[nltk_data]    | Downloading package product_reviews_2 to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package product_reviews_2 is already up-to-date!
[nltk_data]    | Downloading package propbank to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package propbank is already up-to-date!
[nltk_data]    | Downloading package pros_cons to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package pros_cons is already up-to-date!
[nltk_data]    | Downloading package ptb to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package ptb is already up-to-date!
[nltk_data]    | Downloading package punkt to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package punkt is already up-to-date!
[nltk_data]    | Downloading package punkt_tab to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package punkt_tab is already up-to-date!
[nltk_data]    | Downloading package qc to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package qc is already up-to-date!
[nltk_data]    | Downloading package reuters to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package reuters is already up-to-date!
[nltk_data]    | Downloading package rslp to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package rslp is already up-to-date!
[nltk_data]    | Downloading package rte to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package rte is already up-to-date!
[nltk_data]    | Downloading package sample_grammars to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package sample_grammars is already up-to-date!
[nltk_data]    | Downloading package semcor to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package semcor is already up-to-date!
[nltk_data]    | Downloading package senseval to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package senseval is already up-to-date!
[nltk_data]    | Downloading package sentence_polarity to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package sentence_polarity is already up-to-date!
[nltk_data]    | Downloading package sentiwordnet to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package sentiwordnet is already up-to-date!
[nltk_data]    | Downloading package shakespeare to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package shakespeare is already up-to-date!
[nltk_data]    | Downloading package sinica_treebank to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package sinica_treebank is already up-to-date!
[nltk_data]    | Downloading package smultron to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package smultron is already up-to-date!
[nltk_data]    | Downloading package snowball_data to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package snowball_data is already up-to-date!
[nltk_data]    | Downloading package spanish_grammars to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package spanish_grammars is already up-to-date!
[nltk_data]    | Downloading package state_union to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package state_union is already up-to-date!
[nltk_data]    | Downloading package stopwords to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package stopwords is already up-to-date!
[nltk_data]    | Downloading package subjectivity to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package subjectivity is already up-to-date!
[nltk_data]    | Downloading package swadesh to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package swadesh is already up-to-date!
[nltk_data]    | Downloading package switchboard to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package switchboard is already up-to-date!
[nltk_data]    | Downloading package tagsets to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package tagsets is already up-to-date!
[nltk_data]    | Downloading package tagsets_json to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package tagsets_json is already up-to-date!
[nltk_data]    | Downloading package timit to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package timit is already up-to-date!
[nltk_data]    | Downloading package toolbox to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package toolbox is already up-to-date!
[nltk_data]    | Downloading package treebank to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package treebank is already up-to-date!
[nltk_data]    | Downloading package twitter_samples to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package twitter_samples is already up-to-date!
[nltk_data]    | Downloading package udhr to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package udhr is already up-to-date!
[nltk_data]    | Downloading package udhr2 to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package udhr2 is already up-to-date!
[nltk_data]    | Downloading package unicode_samples to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package unicode_samples is already up-to-date!
[nltk_data]    | Downloading package universal_tagset to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package universal_tagset is already up-to-date!
[nltk_data]    | Downloading package universal_treebanks_v20 to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package universal_treebanks_v20 is already up-to-
[nltk_data]    |       date!
[nltk_data]    | Downloading package vader_lexicon to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package vader_lexicon is already up-to-date!
[nltk_data]    | Downloading package verbnet to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package verbnet is already up-to-date!
[nltk_data]    | Downloading package verbnet3 to
[nltk_data]    |     C:\Users\huonc\AppData\Roaming\nltk_data...
[nltk_data]    |   Package verbnet3 is already up-to-date!
[nltk_data]    | Downloading package webtext to

(29517, 7415, 36932)

In [8]:
#turn to pandas dataframe
df_train = pd.DataFrame({'sentences': train_processed})
df_test = pd.DataFrame({'sentences': test_processed})
df_val = pd.DataFrame({'sentences': val_processed})

In [9]:
analyzer = SentimentIntensityAnalyzer()

def get_sentiment(text):
    scores = analyzer.polarity_scores(text)
    if scores['pos'] > 0:
        sentiment = 1
    else:
        sentiment = 0
    return sentiment 

df_train['sentiment'] = df_train['sentences'].apply(get_sentiment)
df_test['sentiment'] = df_test['sentences'].apply(get_sentiment)
df_val['sentiment'] = df_val['sentences'].apply(get_sentiment)

In [10]:
from nltk.corpus import opinion_lexicon
negative_words = list(opinion_lexicon.negative())
negative_words[:10]

['2-faced',
 '2-faces',
 'abnormal',
 'abolish',
 'abominable',
 'abominably',
 'abominate',
 'abomination',
 'abort',
 'aborted']

In [11]:
#make a new column that shows positive sentence 
#expand contractions

%pip install contractions
%pip install swifter
import swifter
import contractions

negative_words = set(opinion_lexicon.negative())

def set_positive(sentence):
    expanded = contractions.fix(sentence)
    words = word_tokenize(expanded.lower())
    for i in words:
        if i in negative_words:
            return 0
    return 1

df_train['positive'] = df_train['sentences'].swifter.apply(set_positive)
df_test['positive'] = df_test['sentences'].swifter.apply(set_positive)
df_val['positive'] = df_val['sentences'].swifter.apply(set_positive)

Requirement already satisfied: contractions in c:\users\huonc\desktop\python\mining_project\venv\lib\site-packages (0.1.73)
Requirement already satisfied: textsearch>=0.0.21 in c:\users\huonc\desktop\python\mining_project\venv\lib\site-packages (from contractions) (0.0.24)
Requirement already satisfied: anyascii in c:\users\huonc\desktop\python\mining_project\venv\lib\site-packages (from textsearch>=0.0.21->contractions) (0.3.2)
Requirement already satisfied: pyahocorasick in c:\users\huonc\desktop\python\mining_project\venv\lib\site-packages (from textsearch>=0.0.21->contractions) (2.2.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: swifter in c:\users\huonc\desktop\python\mining_project\venv\lib\site-packages (1.4.0)
Requirement already satisfied: pandas>=1.0.0 in c:\users\huonc\desktop\python\mining_project\venv\lib\site-packages (from swifter) (2.3.0)
Requirement already satisfied: psutil>=5.6.6 in c:\users\huonc\desktop\python\mining_project\venv\lib\site-packages (from swifter) (7.0.0)
Requirement already satisfied: dask>=2.10.0 in c:\users\huonc\desktop\python\mining_project\venv\lib\site-packages (from dask[dataframe]>=2.10.0->swifter) (2025.5.1)
Requirement already satisfied: tqdm>=4.33.0 in c:\users\huonc\desktop\python\mining_project\venv\lib\site-packages (from swifter) (4.67.1)
Requirement already satisfied: click>=8.1 in c:\users\huonc\desktop\python\mining_project\venv\lib\site-packages (from dask>=2.10.0->dask[dataframe]>=2.10.0->swifter) (8.2.1)
Requirement already satisfied: cloudpickle>=3.0.0 in c:\users\huonc\desktop\python\mining_project\venv\lib\site-packages (from dask>=2.10.0->dask[dataframe]>=2.10.0->swifter) (3.1.1)
Requirement already satisfied: fsspec>=2021.09.0 in c:\users\huonc\desktop\python\mining_project\venv\lib\site-packages (from dask>=2.10.0->dask[dataframe]>=2.10.0->swifter) (2025.3.0)
Requirement already satisfied: packaging>=20.0 in c:\users\huonc\desktop\python\mining_project\venv\lib\site-packages (from dask>=2.10.0->dask[dataframe]>=2.10.0->swifter) (25.0)
Requirement already satisfied: partd>=1.4.0 in c:\users\huonc\desktop\python\mining_project\venv\lib\site-packages (from dask>=2.10.0->dask[dataframe]>=2.10.0->swifter) (1.4.2)
Requirement already satisfied: pyyaml>=5.3.1 in c:\users\huonc\desktop\python\mining_project\venv\lib\site-packages (from dask>=2.10.0->dask[dataframe]>=2.10.0->swifter) (6.0.2)
Requirement already satisfied: toolz>=0.10.0 in c:\users\huonc\desktop\python\mining_project\venv\lib\site-packages (from dask>=2.10.0->dask[dataframe]>=2.10.0->swifter) (1.0.0)
Requirement already satisfied: importlib_metadata>=4.13.0 in c:\users\huonc\desktop\python\mining_project\venv\lib\site-packages (from dask>=2.10.0->dask[dataframe]>=2.10.0->swifter) (8.7.0)
Requirement already satisfied: colorama in c:\users\huonc\desktop\python\mining_project\venv\lib\site-packages (from click>=8.1->dask>=2.10.0->dask[dataframe]>=2.10.0->swifter) (0.4.6)
Requirement already satisfied: pyarrow>=14.0.1 in c:\users\huonc\desktop\python\mining_project\venv\lib\site-packages (from dask[dataframe]>=2.10.0->swifter) (20.0.0)
Requirement already satisfied: zipp>=3.20 in c:\users\huonc\desktop\python\mining_project\venv\lib\site-packages (from importlib_metadata>=4.13.0->dask>=2.10.0->dask[dataframe]>=2.10.0->swifter) (3.23.0)
Requirement already satisfied: numpy>=1.23.2 in c:\users\huonc\desktop\python\mining_project\venv\lib\site-packages (from pandas>=1.0.0->swifter) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\huonc\desktop\python\mining_project\venv\lib\site-packages (from pandas>=1.0.0->swifter) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\huonc\desktop\python\mining_project\venv\lib\site-packages (from pandas>=1.0.0->swifter) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\huonc\desktop\python\mining_project\venv\lib\site-packages (from pandas>=1.0.0->swifter) (2025.2)
Requirement already satisfied: locket in c:\users\huonc\desktop\python\mining_project\venv\lib\site-packages (from partd>=1.4.0->dask>=2.10.0->dask[dataframe]>=2.10.0->swifter) (1.0.0)
Requirement already satisfied: six>=1.5 in c:\users\huonc\desktop\python\mining_project\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->swifter) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

Pandas Apply:   0%|          | 0/29517 [00:00<?, ?it/s]

Pandas Apply:   0%|          | 0/7415 [00:00<?, ?it/s]

Pandas Apply:   0%|          | 0/36932 [00:00<?, ?it/s]

In [12]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(df_train['positive'], df_train['sentiment']))

[[ 3935 10234]
 [ 7909  7439]]

Confusion matrix: *many errors*

### Using VADER sentiment scoring

* bag of words

In [13]:
from nltk.sentiment import SentimentIntensityAnalyzer
from tqdm.notebook import tqdm 

sia = SentimentIntensityAnalyzer()

In [14]:
sia.polarity_scores("bad")

{'neg': 1.0, 'neu': 0.0, 'pos': 0.0, 'compound': -0.5423}

In [15]:
df_train.reset_index(inplace = True)
df_test.reset_index(inplace = True)
df_val.reset_index(inplace = True)

In [16]:
#polarity score on the entire train dataset
result = {}
for i, row in tqdm(df_train.iterrows(), total = len(df_train)):
    text = row['sentences']
    myid = row['index']
    result[myid] = sia.polarity_scores(text)

  0%|          | 0/29517 [00:00<?, ?it/s]

In [17]:
vaders = pd.DataFrame(result).T
vaders = vaders.reset_index()
vaders = vaders.merge(df_train, how = "left")

In [18]:
vaders.head()

,index,neg,neu,pos,compound,sentences,sentiment,positive
0,0,0.158,0.639,0.203,0.4939,comment grandparent greatestwhatever greatest ...,1,0
1,1,0.000,0.769,0.231,0.0516,comment grey cloudy today anyway,1,0
2,2,0.000,0.566,0.434,0.3182,comment assume meant greet,1,1
3,3,0.630,0.370,0.000,-0.5267,violator fed bear,0,0
4,4,0.240,0.549,0.210,-0.0844,personal fan literally dont care anyone else t...,1,1

In [19]:
vaders.shape

(29517, 8)

### Roberta Pretrained Model

* train the dataset

In [20]:
#%pip install transformers
from transformers import AutoTokenizer
from transformers import AutoModelForSequenceClassification
from scipy.special import softmax

In [21]:
MODEL = f"cardiffnlp/twitter-roberta-base-sentiment"
tokenizer = AutoTokenizer.from_pretrained(MODEL)
model = AutoModelForSequenceClassification.from_pretrained(MODEL)

config.json:   0%|          | 0.00/747 [00:00<?, ?B/s]

c:\Users\huonc\Desktop\python\mining_project\venv\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\huonc\.cache\huggingface\hub\models--cardiffnlp--twitter-roberta-base-sentiment. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/150 [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

pytorch_model.bin:   0%|          | 0.00/499M [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

In [22]:
#vader
test = df_train['sentences'][50]
print(test)
sia.polarity_scores(test)

comment youd assume position get fucked small peasant revolt actual witch hunter hearing murmuring know sign look determining one witch legitimate wizard one messing thing

{'neg': 0.299, 'neu': 0.701, 'pos': 0.0, 'compound': -0.8555}

In [29]:
def polarity_scores_roberta(example):
    #roberta model
    encoded_text = tokenizer(test, return_tensors="pt")
    out = model(**encoded_text)
    scores = out[0][0].detach().numpy()
    scores = softmax(scores) #neg, neu, pos
    scores_dict = {
        'roberta_neg': scores[0],
        'roberta_neu': scores[1],
        'roberta_pos': scores[2]
    }
    scores_dict

    return scores_dict

In [33]:
#polarity score on the entire train dataset
result = {}
for i, row in tqdm(df_train.iterrows(), total = len(df_train)):
    text = row['sentences']
    myid = row['index']
    vader_result = sia.polarity_scores(text)

    vader_result_rename = {}
    for key, value in vader_result.items():
        vader_result_rename[f"vader_{key}"] = value
    roberta_result = polarity_scores_roberta(text)

    both = {**vader_result, **roberta_result}
    result[myid] = both

  0%|          | 0/29517 [00:00<?, ?it/s]

In [ ]:
both

{'neg': 0.158,
 'neu': 0.639,
 'pos': 0.203,
 'compound': 0.4939,
 'roberta_neg': 0.542965,
 'roberta_neu': 0.44426653,
 'roberta_pos': 0.012768475}

In [34]:
results_df = pd.DataFrame(result).T
results_df = results_df.reset_index()
results_df = results_df.merge(df_train, how = "left")

In [35]:
results_df.head()

,index,neg,neu,pos,compound,roberta_neg,roberta_neu,roberta_pos,sentences,sentiment,positive
0,0,0.158,0.639,0.203,0.4939,0.542965,0.444267,0.012768,comment grandparent greatestwhatever greatest ...,1,0
1,1,0.000,0.769,0.231,0.0516,0.542965,0.444267,0.012768,comment grey cloudy today anyway,1,0
2,2,0.000,0.566,0.434,0.3182,0.542965,0.444267,0.012768,comment assume meant greet,1,1
3,3,0.630,0.370,0.000,-0.5267,0.542965,0.444267,0.012768,violator fed bear,0,0
4,4,0.240,0.549,0.210,-0.0844,0.542965,0.444267,0.012768,personal fan literally dont care anyone else t...,1,1

In [36]:
from transformers import pipeline 

sentiment_pipeline = pipeline("sentiment-analysis")

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

c:\Users\huonc\Desktop\python\mining_project\venv\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\huonc\.cache\huggingface\hub\models--distilbert--distilbert-base-uncased-finetuned-sst-2-english. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

Device set to use cpu

In [37]:
sentiment_pipeline("not bad, it's just ok")

[{'label': 'POSITIVE', 'score': 0.9998577833175659}]

In [40]:
sentiment_pipeline("not bad, he's a successfully failed the mission")

[{'label': 'POSITIVE', 'score': 0.9959104061126709}]